# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f8792a92b703c61c319ad947deed0748b2d262e58c69609861ba36cc982fcce070fc95440c81318bf908799e611ef91a900a501721dd7e0c162ad2f9007bbf1

test:
  secret_key_base: e9c9dc0fb0f119d31a79b6f136cc06240f5f1d4460b77c6d1616f1038ae24eeb85f890613d00dae00b0dc3a8914a7b45615e1525182cfbc67e62e208edfe06c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
